# https://github.com/khezen/compose-postgres
version: '2'
services:  
  postgres:
    image: postgres:12.2
    restart: always
    container_name: social-network-auth-microservice.postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: social_network
      POSTGRES_USER: social_network
      POSTGRES_PASSWORD: social_network
    volumes:
      - postgres-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    container_name: social-network-auth-microservice.pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 3309:80
  node:
    build: .
    command: /app/node_modules/.bin/nodemon ./server.js
    container_name: social-network-auth-microservice.node
    ports:
      - 3000:3000
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
volumes:
  postgres-data: